dist: bionic
language: cpp
script:
<<<<<<< HEAD
<<<<<<< HEAD
=======
  - cmake CMakeLists.txt
  - cmake --build .
>>>>>>> Update .travis.yml
  after_success:
  - bash <(curl -s https://codecov.io/bash)
=======
>>>>>>> simple travis
