language: c
os:
  - linux
compiler:
  - gcc
env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
install:
  - sudo apt-get install cmake
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
script:
<<<<<<< HEAD
  - mkrdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
  - cmake ..build
=======
  - cmake CMakeLists.txt
  - cmake --build .
>>>>>>> Update .travis.yml
