language: c
os:
  - linux
compiler:
  - gcc
install:
  - sudo apt-get install cmake
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
script:
<<<<<<< HEAD
=======
  - cmake CMakeLists.txt
  - cmake --build .
>>>>>>> Update .travis.yml
  after_success:
  - bash <(curl -s https://codecov.io/bash)
